### PR TITLE
Allowing for pip installation as a module

### PR DESCRIPTION
**Pull request by pykler**

### CODE REVIEW

**Comment by D4Vinci** [comment]
Thanks! :smile:

**Comment by D4Vinci** [comment]
Fixed a lot of errors btw, check out the commits

**Comment by pykler** [comment]
You mean in the README file? I might have missed a few changes. Was there anything broken in the code?

**Comment by D4Vinci** [comment]
Yup, the check for update feature but I fixed everything I just thought you should know

**Comment by pykler** [comment]
There is one more small thing, sending a PR now.

**Pull request merged**
